-- Simple fix for missing database components

-- Add missing columns to profiles table 
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS software text[];

-- Create profiles_professional_roles junction table
CREATE TABLE IF NOT EXISTS profiles_professional_roles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  role text NOT NULL,
  created_at timestamp with time zone DEFAULT now()
);

-- Enable RLS
ALTER TABLE profiles_professional_roles ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY IF NOT EXISTS "Public read access to professional roles" 
ON profiles_professional_roles 
FOR SELECT 
USING (true);

CREATE POLICY IF NOT EXISTS "Users can manage their own professional roles" 
ON profiles_professional_roles 
FOR ALL 
USING (profile_id = auth.uid());