CREATE TABLE public.portfolio_media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
    file_url TEXT NOT NULL,
    file_type TEXT NOT NULL, -- e.g., 'image', 'audio', 'video', 'document'
    title TEXT,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE public.portfolio_media ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow users to view their own portfolio media" ON public.portfolio_media
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Allow users to insert their own portfolio media" ON public.portfolio_media
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Allow users to update their own portfolio media" ON public.portfolio_media
FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Allow users to delete their own portfolio media" ON public.portfolio_media
FOR DELETE USING (auth.uid() = user_id);

-- Allow public read access to portfolio media
CREATE POLICY "Allow public read access to portfolio media" ON public.portfolio_media
FOR SELECT TO anon, authenticated USING (true);